[package]
name = "data_linker"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
rumqttc = "0.25.0"
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "1.1"
rand = "0.8.5"
